### ISSUE TITLE
Что означает, когда папка venv подсвечивается (см. скриншот)

### ISSUE THREAD

**Issue by edwardaxm** [edwardaxm/python-test#1]
![3](https://user-images.githubusercontent.com/45208229/48914768-7c6b3400-ee8d-11e8-9057-7cf8d515718e.jpg)
> Получается проекты в PyCharm копировать нельзя, только создавать новый и уже в него переносить файлы .py?

**Comment by coursar** [comment]
Это означает, что в PyCharm вы её добавили в Excluded (т.е. он не индексирует её и не осуществляет поиск по ней):

![default](https://user-images.githubusercontent.com/3601892/49265520-7bc13780-f463-11e8-923b-a3d835037ae3.png)

Чтобы убрать из Excluded, нужно зайти в настройки проекта и убрать:

![2](https://user-images.githubusercontent.com/3601892/49265538-8ed40780-f463-11e8-8903-0322866c6568.png)
