### ISSUE TITLE
Проверить ДЗ "DocTest в PyTest"

### ISSUE THREAD

**Issue by edwardaxm** [edwardaxm/python-test#3]
Посмотрите пожалуйста, если я правильно понял задание.

**Comment by coursar** [comment]
@edwardaxm, нужно было сохранить структуру каталогов + модули должны называться не first, second - а отражать логическую суть (cashback, bonus и т.д.) и тесты соответственно.

**Comment by coursar** [comment]
@edwardaxm, обновил репозиторий. Тесты нужно именовать так, чтобы по названиям было понятно, что же они тестируют.
