### ISSUE TITLE
Убрать каталоги venv, .idea, __pycache__ из репозитория

### ISSUE THREAD

**Issue by coursar** [edwardaxm/python-test#4]

**Comment by edwardaxm** [comment]
@coursar, их как-то можно по отдельности удалить или лучше перезалить весь проект?

Исправлено - fe0eed81c5970f1b404958bd4b9cd96cebef9300

**Comment by coursar** [comment]
`git rm -r .idea` и т.д. После чего добавить в .gitignore.
